---
# File: main.yml - Main tasks for Consul

- name: Looking up latest version of Consul
  set_fact:
    consul_version: "{{ (lookup('url', 'https://api.github.com/repos/hashicorp/consul/releases/latest', split_lines=False) |
                    from_json).get('tag_name') | replace('v', '') }}"
  when: 'consul_version == "latest"'

- name: Pip config file create
  file:
    path: /etc/pip.conf
    mode: "0444"
    state: touch
  register: script_file_created

- name: Pip configure
  blockinfile:
    path: /etc/pip.conf
    content: |
        [global]
        index-url = https://pypi.tuna.tsinghua.edu.cn/simple
  when: script_file_created.changed

- name: Source activate
  shell: |
    source /runner/bin/activate
  args:
    executable: /bin/bash
  environment:
    HOME: /runner
  become: false


# - name: Install virtualenv package on the controlling host
#   pip:
#     name: virtualenv
#     executable: pip3
#     state: present
#   delegate_to: 127.0.0.1
#   become: false
#   run_once: true

# - name: Create a Python virtual environment
#   command: virtualenv consul-site
#   args:
#     chdir: /runner/
#   become: true

- name: Install python dependencies
  when: consul_install_dependencies | bool
  block:
    - name: Install netaddr dependency on controlling host (with --user)
      pip:
        name: netaddr
        executable: pip3
        extra_args: --user
      delegate_to: 127.0.0.1
      become: false
      vars:
        ansible_become: false
      run_once: true
      when: not is_virtualenv or is_virtualenv == None

    - name: Install netaddr dependency on controlling host (virtualenv)
      pip:
        name: netaddr
        executable: pip3
      delegate_to: 127.0.0.1
      become: false
      vars:
        ansible_become: false
      run_once: true
      when: is_virtualenv is defined

- name: Include checks/asserts
  import_tasks: asserts.yml

- name: Print variables
  debug:
    var: "{{ item }}"
  loop:
    - vars_file_item
    - ansible_os_family
    - ansible_distribution_major_version
- name: Include OS-specific variables
  include_vars: "{{ vars_file_item }}"
  with_first_found:
    - files:
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
        - "{{ ansible_os_family }}.yml"
  loop_control:
    loop_var: vars_file_item
  tags: always

# -----------------------------------------------------------------------
# Tasks for all *NIX operating systems
# -----------------------------------------------------------------------
- name: Include NIX tasks
  include_tasks: nix.yml
  when: ansible_os_family != 'Windows'

# -----------------------------------------------------------------------
# Tasks for Windows
# -----------------------------------------------------------------------
- name: Include Windows tasks
  include_tasks: windows.yml
  when: ansible_os_family == 'Windows'

- name: Include services management
  import_tasks: services.yml
  when: consul_services is defined and consul_services|length>0
  tags:
    - consul_services

- name: Flush handlers
  meta: flush_handlers
